name: Build APK with Buildozer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies and Android SDK
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-dev git build-essential \
                            openjdk-11-jdk unzip zlib1g-dev libffi-dev wget
        pip install --upgrade cython buildozer virtualenv

        # تحميل SDK Tools
        mkdir -p $HOME/Android/Sdk/cmdline-tools
        cd $HOME/Android/Sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mv cmdline-tools latest

        # قبول تراخيص Android SDK
        yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --licenses

        # تثبيت أدوات Build-Tools وplatforms المطلوبة
        $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Set environment variables for Buildozer
      run: |
        echo "export ANDROID_SDK_ROOT=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "export PATH=$HOME/Android/Sdk/platform-tools:$HOME/Android/Sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

    - name: Build APK with Buildozer
      run: |
        cd $GITHUB_WORKSPACE
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: calculator-apk
        path: $GITHUB_WORKSPACE/bin/**/*.apk
